<?php

/**
 * Calculate the sum of two ints.
 *
 * @param int $a The first operand.
 * @param int $b The second operand.
 * @return int The sum of the two numbers.
 */
function add(int $a, int $b): int
{
    // TODO Will be generated by AI
}
