<?php

/**
 * A class that performs basic arithmetic operations.
 */
class Calculator
{
    /** @var int Stores the result of the last operation performed. */
    private int $lastResult = 0;

    /**
     * Calculate the sum of two ints.
     *
     * @param int $a The first operand.
     * @param int $b The second operand.
     * @return int The sum of the two numbers.
     */
    public function add(int $a, int $b): int
    {
        // TODO Will be generated by AI
    }
}
